# Site settings
name: 氢酱的代码们
email: gs199704@gmail.com
author: 二价氢
url: https://ejq.me/
resume_site: https://b.ejq.me/about
github: https://github.com/erjiaqing/
baseurl: ""
description: 一言蔽之，就是爱啊
meta_description: 一言蔽之，就是爱啊
motto: 
banner: 氢酱的代码们

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: erjiaqing
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : disqus
    duoshuo:
        short_name : ejqgithub
    disqus :
        short_name : ejqgithub
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
